### ISSUE TITLE
How to calculate soil water content for each day?

### ISSUE THREAD

**Issue by fclof** [kthorp/pyfao56#44]
I'd like to find a way to output a simulated soil moisture sequence, can I use existing variables (e.g. RAW TAW Zr) to calculate it?

**Comment by fclof** [comment]
I just found that one can calculate soil water content according to FIgure 42 in FAO paper 56

**Comment by isukendall** [comment]
Figure 42 is meant for calculation of the water stress coefficient Ks, as a function of soil water content (theta), when field capacity and wilting point are known or assumed. Or alternately, if RAW and TAW are known. This isn't really designed to reverse-engineer a simulated soil water sequence.

**Comment by kthorp** [comment]
FAO-56 is designed around the concept of soil water depletion relative to the specified field capacity.  A better approach is to likewise compute soil water depletion from the measured soil water sequence.  pyfao56 has tools for doing this in the SoilWaterSeries class.  Also, the Visualization class has tools for plotting measured versus simulated soil water depletion time series.  We are now working on methods for direct assimilation of observed "depletion" into the model. Thanks for your interest in the tool.
