### ISSUE TITLE
Regarding root growth in pyfao56 (line 723)

### ISSUE THREAD

**Issue by dineshgulati933** [kthorp/pyfao56#59]
Hi Kelly: We have recently been working on GDD-based Kcb values and are ingesting those for the whole crop period using the update class. While doing this, I noticed that for the root growth in line 723 in the model class, pyfao56 is using the tkcb value of the current day when it should be kcb (if there is any daily update from the user). Since we are updating Kcb but still pyfao56 is using the tkcb of the day to calculate root depth and thus TAW, can you please advise on this?

![Screenshot 2024-09-13 115349](https://github.com/user-attachments/assets/209c933c-a6c0-4ed1-b078-eaa89bfe251b)

**Comment by kthorp** [comment]
Using tKcb ensures that root growth follows the trapezoidal Kcb curve by default.  In case the Kcb is updated with the Update class, those updates don't apply to the root growth.  I think it gets too messy fairly quickly if updating Kcb applies updates to both Kcb and Zr. A goal is to add Zr to Update, so the Kcb and Zr could be updated independently.

**Comment by dineshgulati933** [comment]
Thanks, Kelly, for your reply. I understand your point, and it may make things messy when users do not expect unintentional changes in the root growth. However, in our case, we are updating only daily Kcbs and don't have any actual data on root development, so we tweaked the code to mimic root growth as per the updated Kcb.


![Screenshot 2024-09-13 153601](https://github.com/user-attachments/assets/c5cb5386-b26e-4069-b303-4b7125c8c2de)
